
apiVersion: apps/v1
kind: Deployment
metadata:
  name: convtemperatura
spec:
  selector:
    matchLabels:
      app: convtemperatura
  template:
    metadata:
      labels:
        app: convtemperatura
    spec:
      containers:
      - name: convtemperatura
        image: seishuku/conversao-temperatura:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: convtemperatura
spec:
  selector:
    app: convtemperatura
  ports:
    - port: 80
      targetPort: 8080 
      nodePort: 30000
  type: NodePort